### ISSUE TITLE
numericFilters?

### ISSUE THREAD

**Issue by MattTimmons** [algolia/algoliasearch-client-swift#46]
I am having difficulty finding numericFilters in the 3.0 SDK..
I used to be able to do a query with a numericFilter to find an record with a specific number.

**Comment by clement-leprovost-algolia** [comment]
Yes. `numericFilters` has been purposely removed because strongly typing it would have been overly complicated. See [Query.swift#45](https://github.com/algolia/algoliasearch-client-swift/blob/master/Source/Query.swift#L45).

Fortunately... you can use the new low-level accessors, passing a plain string:

```
query["numericFilters"] = "[...]"
```
