### ISSUE TITLE
TimeInterval - seconds(_ secondsCount: Int) -> TimeInterval

### ISSUE THREAD

**Issue by tatunn** [algolia/algoliasearch-client-swift#737]
**Describe the bug 🐛**
You have an extension about TimeInterval which has a method seconds(_:) -> TimeInterval
this method already exists

```
public extension TimeInterval {
  static let second: TimeInterval = 1

  static func seconds(_ secondsCount: Int) -> TimeInterval {
        return TimeInterval(secondsCount)
  }
}
```
**To Reproduce 🔍**

**Expected behavior 💭**

**Screenshots 🖥**

**Environment:**

**Additional context**

**Comment by VladislavFitz** [comment]
Hi @tatunn,
I didn't manage to find this method in the standard library. Could you provide more details?

**Comment by yura-hb** [comment]
Hello, it conflicts with `DispatchTimeInterval.seconds`, so when a library is connected we need to specify, which type to use. For example, the next code produces error `ambiguous use of init`, if the library is connected. (Xcode version 12.5)

```
DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1)) {
  // Some code
}
```

So the fix is to specify the type manually. However, I suppose, that the extension of the TimeInterval shouldn't be public.

```
DispatchQueue.main.asyncAfter(deadline: .now() + DispatchTimeInterval.seconds(1)) {

}
```
